version: '3.7'

services:
            
    ssh_honeypot:
        container_name: ssh_honeypot
        build:
          context: .
          dockerfile: Dockerfile
        image: prajwal3498/ssh_honeypot:latest
        tty: true  
        command: python honeypot.py --port 2222
        volumes:
            - .:/app
        env_file:
            - ./.env
        ports:
            - 2224:2222
        environment:
            - CHOKIDAR_USEPOLLING=true
            
    ssh_honeypot_downloader:
        container_name: ssh_honeypot_downloader
        build:
          context: .
          dockerfile: Dockerfile
        image: prajwal3498/ssh_honeypot_downloader:latest
        tty: true  
        command: python honeypot_downloader.py
        volumes:
            - .:/app
        env_file:
            - ./.env
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - "ssh_honeypot_redis_db"
            
    ssh_honeypot_redis_db:
        container_name: ssh_honeypot_redis_db
        image: redis:6.0.7-alpine
        command: redis-server --requirepass password 
        env_file:
            - ./.env